name: release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    permissions:
      contents: write # To publish the release.

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-go
        with:
          fetch-depth: 0

      - uses: goreleaser/goreleaser-action
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
